# Generated by Django 2.2.5 on 2020-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200413_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name=(('usd', 'USD'), ('krw', 'KRW'))),
        ),
        migrations.AddField(
            model_name='user',
            name='langauge',
            field=models.CharField(blank=True, choices=[('en', 'EN'), ('kr', 'KR')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supoerhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
